apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-backend
  namespace: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/tejalkunde/devops-task-manager-backend:db0c07c3fd1cf6e7056f0acb51939cb37c6ad494
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"