apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-manager-ingress
  namespace: task-manager
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: task-backend
                port:
                  number: 5000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-frontend
                port:
                  number: 80