name: Build and Push Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/tejalkunde/devops-task-manager-backend:${{ github.sha }}
            ghcr.io/tejalkunde/devops-task-manager-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/tejalkunde/devops-task-manager-frontend:${{ github.sha }}
            ghcr.io/tejalkunde/devops-task-manager-frontend:latest